# OpenAPI Specification for Physical AI & Humanoid Robotics Textbook

openapi: 3.0.0
info:
  title: Physical AI & Humanoid Robotics Textbook API
  version: 1.0.0
  description: API for the AI-native textbook platform teaching Physical AI and Humanoid Robotics

servers:
  - url: https://api.physical-ai-textbook.com/v1
    description: Production server
  - url: https://staging-api.physical-ai-textbook.com/v1
    description: Staging server

paths:
  /chapters:
    get:
      summary: Get all textbook chapters
      description: Retrieve a list of all 8 chapters in the textbook
      responses:
        '200':
          description: List of chapters
          content:
            application/json:
              schema:
                type: object
                properties:
                  chapters:
                    type: array
                    items:
                      $ref: '#/components/schemas/Chapter'

  /chapters/{chapterId}:
    get:
      summary: Get chapter details
      description: Retrieve details for a specific chapter including lessons
      parameters:
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
          description: Chapter identifier (e.g., "chapter-1")
      responses:
        '200':
          description: Chapter details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chapter'
        '404':
          description: Chapter not found

  /lessons/{lessonId}:
    get:
      summary: Get lesson content
      description: Retrieve content for a specific lesson
      parameters:
        - name: lessonId
          in: path
          required: true
          schema:
            type: string
          description: Lesson identifier (e.g., "lesson-1.1")
      responses:
        '200':
          description: Lesson content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
        '404':
          description: Lesson not found

  /lessons/{lessonId}/translate:
    post:
      summary: Translate lesson to Urdu
      description: Get Urdu translation of lesson content
      parameters:
        - name: lessonId
          in: path
          required: true
          schema:
            type: string
          description: Lesson identifier
      responses:
        '200':
          description: Urdu translation of lesson
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
        '404':
          description: Lesson not found

  /chatbot/query:
    post:
      summary: Query the textbook chatbot
      description: Ask a question to the RAG-powered chatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The question to ask
                context:
                  type: string
                  description: Optional context (chapter/lesson ID)
                userId:
                  type: string
                  description: Optional user ID for personalization
      responses:
        '200':
          description: Chatbot response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The chatbot's response
                  sources:
                    type: array
                    items:
                      type: string
                    description: Source content that informed the response
                  confidence:
                    type: number
                    description: Confidence score (0-1)

  /users/profile:
    post:
      summary: Create or update user profile
      description: Set user experience level and preferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
      responses:
        '200':
          description: User profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'

  /users/{userId}/progress:
    get:
      summary: Get user progress
      description: Retrieve the user's progress through the textbook
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User progress information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProgress'
    put:
      summary: Update user progress
      description: Update the user's progress through the textbook
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProgress'
      responses:
        '200':
          description: User progress updated

components:
  schemas:
    Chapter:
      type: object
      properties:
        id:
          type: string
          description: Chapter identifier
        title:
          type: string
          description: Chapter title
        number:
          type: integer
          description: Chapter number (1-8)
        objectives:
          type: array
          items:
            type: string
          description: Learning objectives
        lessons:
          type: array
          items:
            $ref: '#/components/schemas/Lesson'
        personalization_options:
          $ref: '#/components/schemas/PersonalizationOptions'
        urdu_translation_available:
          type: boolean
          description: Whether Urdu translation is available

    Lesson:
      type: object
      properties:
        id:
          type: string
          description: Lesson identifier
        title:
          type: string
          description: Lesson title
        chapter_id:
          type: string
          description: Associated chapter ID
        number:
          type: integer
          description: Lesson number within chapter (1-3)
        content:
          type: string
          description: Markdown content of the lesson
        concepts:
          type: array
          items:
            type: string
          description: Key concepts covered
        code_examples:
          type: array
          items:
            $ref: '#/components/schemas/CodeExample'
        simulation_exercises:
          type: array
          items:
            $ref: '#/components/schemas/SimulationExercise'
        mental_models:
          type: array
          items:
            $ref: '#/components/schemas/MentalModel'
        urdu_translation_available:
          type: boolean
          description: Whether Urdu translation is available

    CodeExample:
      type: object
      properties:
        id:
          type: string
          description: Example identifier
        title:
          type: string
          description: Example title
        language:
          type: string
          description: Programming language
        code:
          type: string
          description: Code content
        explanation:
          type: string
          description: Explanation of the code
        related_concepts:
          type: array
          items:
            type: string
          description: Related concepts

    SimulationExercise:
      type: object
      properties:
        id:
          type: string
          description: Exercise identifier
        title:
          type: string
          description: Exercise title
        description:
          type: string
          description: Exercise description
        requirements:
          type: array
          items:
            type: string
          description: Software/hardware requirements
        steps:
          type: array
          items:
            type: string
          description: Steps to complete the exercise
        expected_outcomes:
          type: array
          items:
            type: string
          description: Expected outcomes

    MentalModel:
      type: object
      properties:
        id:
          type: string
          description: Model identifier
        title:
          type: string
          description: Model title
        description:
          type: string
          description: Model description
        diagram_reference:
          type: string
          description: Reference to diagram
        related_concepts:
          type: array
          items:
            type: string
          description: Related concepts

    UserProfile:
      type: object
      properties:
        id:
          type: string
          description: User identifier
        software_experience:
          type: string
          enum: [beginner, intermediate, advanced]
          description: User's software experience level
        robotics_experience:
          type: string
          enum: [beginner, intermediate, advanced]
          description: User's robotics experience level
        available_hardware:
          type: string
          enum: [none, simulation_only, rtx_enabled, jetson, cloud, other]
          description: Available hardware for learning
        preferred_language:
          type: string
          enum: [English, Urdu]
          description: Preferred language
        personalization_enabled:
          type: boolean
          description: Whether personalization is enabled

    UserProgress:
      type: object
      properties:
        user_id:
          type: string
          description: User identifier
        chapter_progress:
          type: array
          items:
            $ref: '#/components/schemas/ChapterProgress'
        lesson_progress:
          type: array
          items:
            $ref: '#/components/schemas/LessonProgress'
        completed_lessons:
          type: array
          items:
            type: string
          description: IDs of completed lessons
        current_lesson:
          type: string
          description: ID of current lesson

    ChapterProgress:
      type: object
      properties:
        chapter_id:
          type: string
          description: Chapter identifier
        completed_lessons:
          type: integer
          description: Number of completed lessons in the chapter
        total_lessons:
          type: integer
          description: Total number of lessons in the chapter (always 3)
        personalization_level:
          type: string
          enum: [default, beginner, intermediate, advanced]
          description: Personalization level used

    LessonProgress:
      type: object
      properties:
        lesson_id:
          type: string
          description: Lesson identifier
        completed:
          type: boolean
          description: Whether the lesson is completed
        time_spent:
          type: number
          description: Time spent on lesson in seconds
        notes:
          type: array
          items:
            type: string
          description: User notes on the lesson
        questions_asked:
          type: number
          description: Number of questions asked during the lesson

    PersonalizationOptions:
      type: object
      properties:
        content_depth:
          type: string
          enum: [shallow, standard, deep]
          description: Depth of content explanations
        example_complexity:
          type: string
          enum: [basic, standard, advanced]
          description: Complexity of examples
        prerequisite_review:
          type: boolean
          description: Whether to include prerequisite review
        additional_resources:
          type: boolean
          description: Whether to include additional resources